---
# tasks file for mytom8onU16
- include_tasks: myjavainstall.yml
- include_tasks: tomcatuser.yml
- include_tasks: download.yml
- include_tasks: extract.yml
- include_tasks: Permissions.yml
- include_tasks: configtom.yml
- include_tasks: starttom.yml
